// <auto-generated>
//   Generated from Tuning.cs. One entry per Default* constant there: the live value, the
//   assignment that reads it from the config file, its row in the Parameters table, and its
//   contribution to the fingerprint. Do not hand-edit — add the constant to Tuning.cs and
//   regenerate, or the four lists here fall out of step with each other.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Globalization;

namespace Archivist.Generation
{
    /// <summary>
    /// The live tuning values, and the table that describes them.
    ///
    /// <para><b>Why there are two shapes of the same field.</b> This assembly compiles twice —
    /// once with <c>UNITY_EDITOR</c> defined, once without — and the two builds want opposite
    /// things. Editorial work wants a value that can be dragged in a window and seen
    /// immediately; a shipped game wants a value the JIT can fold into a literal, which it can
    /// only do for something that cannot change. So the editor gets settable properties and the
    /// player gets <c>static readonly</c>.</para>
    ///
    /// <para><b>Measured, not assumed.</b> Island generation, median of ten, same machine:
    /// <c>const</c> 478/492 ms, <c>static readonly</c> 472/481 ms, settable properties
    /// 565/534 ms. Freezing costs nothing against <c>const</c>; leaving them writable costs
    /// about 13%. The determinism hash (A2) was <c>2933DCFC3DB132D5</c> under all three, so the
    /// two builds cannot generate different islands — only one of them can be edited while it
    /// runs.</para>
    ///
    /// <para><b>Read once, at type-initialisation.</b> Not lazily, not per island, and not from
    /// a composition root: there are four of those — editor, player, acceptance harness, test
    /// runner — and a value configured only where somebody remembered to configure it is a
    /// value silently defaulted in whichever one was forgotten. A static constructor runs
    /// exactly once per domain, before any other member of the class can be touched, which is
    /// the one hook that cannot be skipped.</para>
    ///
    /// <para><b>The identity consequence.</b> R1.11 makes an island a pure function of its
    /// seed; it is now a pure function of its seed <i>and</i> these numbers. Change one and
    /// every seed in the archive means a different island — sheet 7 of the Land Survey keeps
    /// its number while the ground beneath it moves, so every <c>SheetId</c> in a ledger or a
    /// binder points somewhere new. <see cref="Fingerprint"/> exists so that is detectable
    /// rather than silent.</para>
    /// </summary>
    public static partial class Tuning
    {
#if UNITY_EDITOR
        // Settable so the Tuning window can drag a value and regenerate. Internal setters: the
        // window goes through Parameter.Set, so there is one write path to find.
        public static double DomainMetres { get; internal set; } = DefaultDomainMetres;
        public static double NominalRadiusFrac { get; internal set; } = DefaultNominalRadiusFrac;
        public static double NominalRadiusJitter { get; internal set; } = DefaultNominalRadiusJitter;
        public static double SeaLevel { get; internal set; } = DefaultSeaLevel;
        public static double FeatureScale { get; internal set; } = DefaultFeatureScale;
        public static double WarpAmp { get; internal set; } = DefaultWarpAmp;
        public static int    FbmOctaves { get; internal set; } = DefaultFbmOctaves;
        public static double FbmLacunarity { get; internal set; } = DefaultFbmLacunarity;
        public static double FbmGain { get; internal set; } = DefaultFbmGain;
        public static double MaxDepth { get; internal set; } = DefaultMaxDepth;
        public static double MountainousEdge0 { get; internal set; } = DefaultMountainousEdge0;
        public static double MountainousEdge1 { get; internal set; } = DefaultMountainousEdge1;
        public static double FjordedEdge0 { get; internal set; } = DefaultFjordedEdge0;
        public static double FjordedEdge1 { get; internal set; } = DefaultFjordedEdge1;
        public static double FjordedCutAmplitude { get; internal set; } = DefaultFjordedCutAmplitude;
        public static double FjordedCutFrequency { get; internal set; } = DefaultFjordedCutFrequency;
        public static double AtollRingRadius { get; internal set; } = DefaultAtollRingRadius;
        public static double AtollRingCore { get; internal set; } = DefaultAtollRingCore;
        public static double AtollRingWidth { get; internal set; } = DefaultAtollRingWidth;
        public static double BaseCell { get; internal set; } = DefaultBaseCell;
        public static double PaperDetailMm { get; internal set; } = DefaultPaperDetailMm;
        public static int    MaxLod { get; internal set; } = DefaultMaxLod;
        public static double ContourStep { get; internal set; } = DefaultContourStep;
        public static double WeldFraction { get; internal set; } = DefaultWeldFraction;
        public static double MmPerMetre { get; internal set; } = DefaultMmPerMetre;
        public static int    MaxPaperContourLod { get; internal set; } = DefaultMaxPaperContourLod;
        public static int    CoastlineMarginCells { get; internal set; } = DefaultCoastlineMarginCells;
        public static double GradientStep { get; internal set; } = DefaultGradientStep;
        public static double SheetWidthMm { get; internal set; } = DefaultSheetWidthMm;
        public static double SheetHeightMm { get; internal set; } = DefaultSheetHeightMm;
        public static double SheetMarginMm { get; internal set; } = DefaultSheetMarginMm;
        public static int    QuarterScaleFineDenominator { get; internal set; } = DefaultQuarterScaleFineDenominator;
        public static int    QuarterScaleDenominator { get; internal set; } = DefaultQuarterScaleDenominator;
        public static int    WholeIslandScaleDenominator { get; internal set; } = DefaultWholeIslandScaleDenominator;
        public static int    WholeIslandFallbackScaleDenominator { get; internal set; } = DefaultWholeIslandFallbackScaleDenominator;
        public static double GridPitchPaperMm { get; internal set; } = DefaultGridPitchPaperMm;
        public static double ServiceRadiusFrac { get; internal set; } = DefaultServiceRadiusFrac;
        public static double ServedThreshold { get; internal set; } = DefaultServedThreshold;
        public static double SoundingDepth { get; internal set; } = DefaultSoundingDepth;
        public static int    CullSampleGrid { get; internal set; } = DefaultCullSampleGrid;
        public static double PeakElevationFrac { get; internal set; } = DefaultPeakElevationFrac;
        public static double PeakNmsRadius { get; internal set; } = DefaultPeakNmsRadius;
        public static int    PeakNamedCount { get; internal set; } = DefaultPeakNamedCount;
        public static double SettlementLattice { get; internal set; } = DefaultSettlementLattice;
        public static double SettlementCoastDist { get; internal set; } = DefaultSettlementCoastDist;
        public static double SettlementFlatGrad { get; internal set; } = DefaultSettlementFlatGrad;
        public static double SettlementShelterRadius { get; internal set; } = DefaultSettlementShelterRadius;
        public static double SettlementMinSpacing { get; internal set; } = DefaultSettlementMinSpacing;
        public static double SettlementShelterWeight { get; internal set; } = DefaultSettlementShelterWeight;
        public static double SettlementFlatnessWeight { get; internal set; } = DefaultSettlementFlatnessWeight;
        public static double RiverStep { get; internal set; } = DefaultRiverStep;
        public static double RiverJitterRad { get; internal set; } = DefaultRiverJitterRad;
        public static double RiverMergeDist { get; internal set; } = DefaultRiverMergeDist;
        public static int    RiverMaxSteps { get; internal set; } = DefaultRiverMaxSteps;
        public static double RiverMinLength { get; internal set; } = DefaultRiverMinLength;
        public static double SoundingLattice { get; internal set; } = DefaultSoundingLattice;
        public static double PeakLattice { get; internal set; } = DefaultPeakLattice;
        public static double PoiLattice { get; internal set; } = DefaultPoiLattice;
        public static double PoiMinSpacing { get; internal set; } = DefaultPoiMinSpacing;
        public static int    PoiCountMountainousMin { get; internal set; } = DefaultPoiCountMountainousMin;
        public static int    PoiCountMountainousMax { get; internal set; } = DefaultPoiCountMountainousMax;
        public static int    PoiCountFjordedMin { get; internal set; } = DefaultPoiCountFjordedMin;
        public static int    PoiCountFjordedMax { get; internal set; } = DefaultPoiCountFjordedMax;
        public static int    PoiCountAtollMin { get; internal set; } = DefaultPoiCountAtollMin;
        public static int    PoiCountAtollMax { get; internal set; } = DefaultPoiCountAtollMax;
        public static double PoiShoreBand { get; internal set; } = DefaultPoiShoreBand;
        public static double PoiSteepShoreGrad { get; internal set; } = DefaultPoiSteepShoreGrad;
        public static double PoiSeaArchGrad { get; internal set; } = DefaultPoiSeaArchGrad;
        public static double PoiBlowholeCoastDist { get; internal set; } = DefaultPoiBlowholeCoastDist;
        public static double PoiSpringMinElevation { get; internal set; } = DefaultPoiSpringMinElevation;
        public static double PoiSpringConvergence { get; internal set; } = DefaultPoiSpringConvergence;
        public static double PoiOpenGrad { get; internal set; } = DefaultPoiOpenGrad;
        public static double PoiFlatGrad { get; internal set; } = DefaultPoiFlatGrad;
        public static double PoiModerateGradMin { get; internal set; } = DefaultPoiModerateGradMin;
        public static double PoiModerateGradMax { get; internal set; } = DefaultPoiModerateGradMax;
        public static double PoiErraticElevMinFrac { get; internal set; } = DefaultPoiErraticElevMinFrac;
        public static double PoiErraticElevMaxFrac { get; internal set; } = DefaultPoiErraticElevMaxFrac;
        public static double PoiTreeElevMinFrac { get; internal set; } = DefaultPoiTreeElevMinFrac;
        public static double PoiTreeElevMaxFrac { get; internal set; } = DefaultPoiTreeElevMaxFrac;
        public static double PoiTreeSettlementDist { get; internal set; } = DefaultPoiTreeSettlementDist;
        public static double PoiChapelSettlementDist { get; internal set; } = DefaultPoiChapelSettlementDist;
        public static double PoiTowerPeakDist { get; internal set; } = DefaultPoiTowerPeakDist;
        public static double PoiCairnPeakFrac { get; internal set; } = DefaultPoiCairnPeakFrac;
        public static double PoiHeadlandShelterMax { get; internal set; } = DefaultPoiHeadlandShelterMax;
        public static double PoiJettyShelterMin { get; internal set; } = DefaultPoiJettyShelterMin;
        public static double DetailSheetWidthMm { get; internal set; } = DefaultDetailSheetWidthMm;
        public static double DetailSheetHeightMm { get; internal set; } = DefaultDetailSheetHeightMm;
        public static double DetailSheetMarginMm { get; internal set; } = DefaultDetailSheetMarginMm;
        public static int    PoiScaleDenominator { get; internal set; } = DefaultPoiScaleDenominator;
#else
        // Frozen. Assigned once in the static constructor below and never again, which is what
        // lets the JIT treat each as the literal it almost always is.
        public static readonly double DomainMetres = DefaultDomainMetres;
        public static readonly double NominalRadiusFrac = DefaultNominalRadiusFrac;
        public static readonly double NominalRadiusJitter = DefaultNominalRadiusJitter;
        public static readonly double SeaLevel = DefaultSeaLevel;
        public static readonly double FeatureScale = DefaultFeatureScale;
        public static readonly double WarpAmp = DefaultWarpAmp;
        public static readonly int    FbmOctaves = DefaultFbmOctaves;
        public static readonly double FbmLacunarity = DefaultFbmLacunarity;
        public static readonly double FbmGain = DefaultFbmGain;
        public static readonly double MaxDepth = DefaultMaxDepth;
        public static readonly double MountainousEdge0 = DefaultMountainousEdge0;
        public static readonly double MountainousEdge1 = DefaultMountainousEdge1;
        public static readonly double FjordedEdge0 = DefaultFjordedEdge0;
        public static readonly double FjordedEdge1 = DefaultFjordedEdge1;
        public static readonly double FjordedCutAmplitude = DefaultFjordedCutAmplitude;
        public static readonly double FjordedCutFrequency = DefaultFjordedCutFrequency;
        public static readonly double AtollRingRadius = DefaultAtollRingRadius;
        public static readonly double AtollRingCore = DefaultAtollRingCore;
        public static readonly double AtollRingWidth = DefaultAtollRingWidth;
        public static readonly double BaseCell = DefaultBaseCell;
        public static readonly double PaperDetailMm = DefaultPaperDetailMm;
        public static readonly int    MaxLod = DefaultMaxLod;
        public static readonly double ContourStep = DefaultContourStep;
        public static readonly double WeldFraction = DefaultWeldFraction;
        public static readonly double MmPerMetre = DefaultMmPerMetre;
        public static readonly int    MaxPaperContourLod = DefaultMaxPaperContourLod;
        public static readonly int    CoastlineMarginCells = DefaultCoastlineMarginCells;
        public static readonly double GradientStep = DefaultGradientStep;
        public static readonly double SheetWidthMm = DefaultSheetWidthMm;
        public static readonly double SheetHeightMm = DefaultSheetHeightMm;
        public static readonly double SheetMarginMm = DefaultSheetMarginMm;
        public static readonly int    QuarterScaleFineDenominator = DefaultQuarterScaleFineDenominator;
        public static readonly int    QuarterScaleDenominator = DefaultQuarterScaleDenominator;
        public static readonly int    WholeIslandScaleDenominator = DefaultWholeIslandScaleDenominator;
        public static readonly int    WholeIslandFallbackScaleDenominator = DefaultWholeIslandFallbackScaleDenominator;
        public static readonly double GridPitchPaperMm = DefaultGridPitchPaperMm;
        public static readonly double ServiceRadiusFrac = DefaultServiceRadiusFrac;
        public static readonly double ServedThreshold = DefaultServedThreshold;
        public static readonly double SoundingDepth = DefaultSoundingDepth;
        public static readonly int    CullSampleGrid = DefaultCullSampleGrid;
        public static readonly double PeakElevationFrac = DefaultPeakElevationFrac;
        public static readonly double PeakNmsRadius = DefaultPeakNmsRadius;
        public static readonly int    PeakNamedCount = DefaultPeakNamedCount;
        public static readonly double SettlementLattice = DefaultSettlementLattice;
        public static readonly double SettlementCoastDist = DefaultSettlementCoastDist;
        public static readonly double SettlementFlatGrad = DefaultSettlementFlatGrad;
        public static readonly double SettlementShelterRadius = DefaultSettlementShelterRadius;
        public static readonly double SettlementMinSpacing = DefaultSettlementMinSpacing;
        public static readonly double SettlementShelterWeight = DefaultSettlementShelterWeight;
        public static readonly double SettlementFlatnessWeight = DefaultSettlementFlatnessWeight;
        public static readonly double RiverStep = DefaultRiverStep;
        public static readonly double RiverJitterRad = DefaultRiverJitterRad;
        public static readonly double RiverMergeDist = DefaultRiverMergeDist;
        public static readonly int    RiverMaxSteps = DefaultRiverMaxSteps;
        public static readonly double RiverMinLength = DefaultRiverMinLength;
        public static readonly double SoundingLattice = DefaultSoundingLattice;
        public static readonly double PeakLattice = DefaultPeakLattice;
        public static readonly double PoiLattice = DefaultPoiLattice;
        public static readonly double PoiMinSpacing = DefaultPoiMinSpacing;
        public static readonly int    PoiCountMountainousMin = DefaultPoiCountMountainousMin;
        public static readonly int    PoiCountMountainousMax = DefaultPoiCountMountainousMax;
        public static readonly int    PoiCountFjordedMin = DefaultPoiCountFjordedMin;
        public static readonly int    PoiCountFjordedMax = DefaultPoiCountFjordedMax;
        public static readonly int    PoiCountAtollMin = DefaultPoiCountAtollMin;
        public static readonly int    PoiCountAtollMax = DefaultPoiCountAtollMax;
        public static readonly double PoiShoreBand = DefaultPoiShoreBand;
        public static readonly double PoiSteepShoreGrad = DefaultPoiSteepShoreGrad;
        public static readonly double PoiSeaArchGrad = DefaultPoiSeaArchGrad;
        public static readonly double PoiBlowholeCoastDist = DefaultPoiBlowholeCoastDist;
        public static readonly double PoiSpringMinElevation = DefaultPoiSpringMinElevation;
        public static readonly double PoiSpringConvergence = DefaultPoiSpringConvergence;
        public static readonly double PoiOpenGrad = DefaultPoiOpenGrad;
        public static readonly double PoiFlatGrad = DefaultPoiFlatGrad;
        public static readonly double PoiModerateGradMin = DefaultPoiModerateGradMin;
        public static readonly double PoiModerateGradMax = DefaultPoiModerateGradMax;
        public static readonly double PoiErraticElevMinFrac = DefaultPoiErraticElevMinFrac;
        public static readonly double PoiErraticElevMaxFrac = DefaultPoiErraticElevMaxFrac;
        public static readonly double PoiTreeElevMinFrac = DefaultPoiTreeElevMinFrac;
        public static readonly double PoiTreeElevMaxFrac = DefaultPoiTreeElevMaxFrac;
        public static readonly double PoiTreeSettlementDist = DefaultPoiTreeSettlementDist;
        public static readonly double PoiChapelSettlementDist = DefaultPoiChapelSettlementDist;
        public static readonly double PoiTowerPeakDist = DefaultPoiTowerPeakDist;
        public static readonly double PoiCairnPeakFrac = DefaultPoiCairnPeakFrac;
        public static readonly double PoiHeadlandShelterMax = DefaultPoiHeadlandShelterMax;
        public static readonly double PoiJettyShelterMin = DefaultPoiJettyShelterMin;
        public static readonly double DetailSheetWidthMm = DefaultDetailSheetWidthMm;
        public static readonly double DetailSheetHeightMm = DefaultDetailSheetHeightMm;
        public static readonly double DetailSheetMarginMm = DefaultDetailSheetMarginMm;
        public static readonly int    PoiScaleDenominator = DefaultPoiScaleDenominator;
#endif

        static Tuning()
        {
            TuningFile.Source source = TuningFile.Load();
                DomainMetres = source.Double("DomainMetres", DefaultDomainMetres);
                NominalRadiusFrac = source.Double("NominalRadiusFrac", DefaultNominalRadiusFrac);
                NominalRadiusJitter = source.Double("NominalRadiusJitter", DefaultNominalRadiusJitter);
                SeaLevel = source.Double("SeaLevel", DefaultSeaLevel);
                FeatureScale = source.Double("FeatureScale", DefaultFeatureScale);
                WarpAmp = source.Double("WarpAmp", DefaultWarpAmp);
                FbmOctaves = source.Int("FbmOctaves", DefaultFbmOctaves);
                FbmLacunarity = source.Double("FbmLacunarity", DefaultFbmLacunarity);
                FbmGain = source.Double("FbmGain", DefaultFbmGain);
                MaxDepth = source.Double("MaxDepth", DefaultMaxDepth);
                MountainousEdge0 = source.Double("MountainousEdge0", DefaultMountainousEdge0);
                MountainousEdge1 = source.Double("MountainousEdge1", DefaultMountainousEdge1);
                FjordedEdge0 = source.Double("FjordedEdge0", DefaultFjordedEdge0);
                FjordedEdge1 = source.Double("FjordedEdge1", DefaultFjordedEdge1);
                FjordedCutAmplitude = source.Double("FjordedCutAmplitude", DefaultFjordedCutAmplitude);
                FjordedCutFrequency = source.Double("FjordedCutFrequency", DefaultFjordedCutFrequency);
                AtollRingRadius = source.Double("AtollRingRadius", DefaultAtollRingRadius);
                AtollRingCore = source.Double("AtollRingCore", DefaultAtollRingCore);
                AtollRingWidth = source.Double("AtollRingWidth", DefaultAtollRingWidth);
                BaseCell = source.Double("BaseCell", DefaultBaseCell);
                PaperDetailMm = source.Double("PaperDetailMm", DefaultPaperDetailMm);
                MaxLod = source.Int("MaxLod", DefaultMaxLod);
                ContourStep = source.Double("ContourStep", DefaultContourStep);
                WeldFraction = source.Double("WeldFraction", DefaultWeldFraction);
                MmPerMetre = source.Double("MmPerMetre", DefaultMmPerMetre);
                MaxPaperContourLod = source.Int("MaxPaperContourLod", DefaultMaxPaperContourLod);
                CoastlineMarginCells = source.Int("CoastlineMarginCells", DefaultCoastlineMarginCells);
                GradientStep = source.Double("GradientStep", DefaultGradientStep);
                SheetWidthMm = source.Double("SheetWidthMm", DefaultSheetWidthMm);
                SheetHeightMm = source.Double("SheetHeightMm", DefaultSheetHeightMm);
                SheetMarginMm = source.Double("SheetMarginMm", DefaultSheetMarginMm);
                QuarterScaleFineDenominator = source.Int("QuarterScaleFineDenominator", DefaultQuarterScaleFineDenominator);
                QuarterScaleDenominator = source.Int("QuarterScaleDenominator", DefaultQuarterScaleDenominator);
                WholeIslandScaleDenominator = source.Int("WholeIslandScaleDenominator", DefaultWholeIslandScaleDenominator);
                WholeIslandFallbackScaleDenominator = source.Int("WholeIslandFallbackScaleDenominator", DefaultWholeIslandFallbackScaleDenominator);
                GridPitchPaperMm = source.Double("GridPitchPaperMm", DefaultGridPitchPaperMm);
                ServiceRadiusFrac = source.Double("ServiceRadiusFrac", DefaultServiceRadiusFrac);
                ServedThreshold = source.Double("ServedThreshold", DefaultServedThreshold);
                SoundingDepth = source.Double("SoundingDepth", DefaultSoundingDepth);
                CullSampleGrid = source.Int("CullSampleGrid", DefaultCullSampleGrid);
                PeakElevationFrac = source.Double("PeakElevationFrac", DefaultPeakElevationFrac);
                PeakNmsRadius = source.Double("PeakNmsRadius", DefaultPeakNmsRadius);
                PeakNamedCount = source.Int("PeakNamedCount", DefaultPeakNamedCount);
                SettlementLattice = source.Double("SettlementLattice", DefaultSettlementLattice);
                SettlementCoastDist = source.Double("SettlementCoastDist", DefaultSettlementCoastDist);
                SettlementFlatGrad = source.Double("SettlementFlatGrad", DefaultSettlementFlatGrad);
                SettlementShelterRadius = source.Double("SettlementShelterRadius", DefaultSettlementShelterRadius);
                SettlementMinSpacing = source.Double("SettlementMinSpacing", DefaultSettlementMinSpacing);
                SettlementShelterWeight = source.Double("SettlementShelterWeight", DefaultSettlementShelterWeight);
                SettlementFlatnessWeight = source.Double("SettlementFlatnessWeight", DefaultSettlementFlatnessWeight);
                RiverStep = source.Double("RiverStep", DefaultRiverStep);
                RiverJitterRad = source.Double("RiverJitterRad", DefaultRiverJitterRad);
                RiverMergeDist = source.Double("RiverMergeDist", DefaultRiverMergeDist);
                RiverMaxSteps = source.Int("RiverMaxSteps", DefaultRiverMaxSteps);
                RiverMinLength = source.Double("RiverMinLength", DefaultRiverMinLength);
                SoundingLattice = source.Double("SoundingLattice", DefaultSoundingLattice);
                PeakLattice = source.Double("PeakLattice", DefaultPeakLattice);
                PoiLattice = source.Double("PoiLattice", DefaultPoiLattice);
                PoiMinSpacing = source.Double("PoiMinSpacing", DefaultPoiMinSpacing);
                PoiCountMountainousMin = source.Int("PoiCountMountainousMin", DefaultPoiCountMountainousMin);
                PoiCountMountainousMax = source.Int("PoiCountMountainousMax", DefaultPoiCountMountainousMax);
                PoiCountFjordedMin = source.Int("PoiCountFjordedMin", DefaultPoiCountFjordedMin);
                PoiCountFjordedMax = source.Int("PoiCountFjordedMax", DefaultPoiCountFjordedMax);
                PoiCountAtollMin = source.Int("PoiCountAtollMin", DefaultPoiCountAtollMin);
                PoiCountAtollMax = source.Int("PoiCountAtollMax", DefaultPoiCountAtollMax);
                PoiShoreBand = source.Double("PoiShoreBand", DefaultPoiShoreBand);
                PoiSteepShoreGrad = source.Double("PoiSteepShoreGrad", DefaultPoiSteepShoreGrad);
                PoiSeaArchGrad = source.Double("PoiSeaArchGrad", DefaultPoiSeaArchGrad);
                PoiBlowholeCoastDist = source.Double("PoiBlowholeCoastDist", DefaultPoiBlowholeCoastDist);
                PoiSpringMinElevation = source.Double("PoiSpringMinElevation", DefaultPoiSpringMinElevation);
                PoiSpringConvergence = source.Double("PoiSpringConvergence", DefaultPoiSpringConvergence);
                PoiOpenGrad = source.Double("PoiOpenGrad", DefaultPoiOpenGrad);
                PoiFlatGrad = source.Double("PoiFlatGrad", DefaultPoiFlatGrad);
                PoiModerateGradMin = source.Double("PoiModerateGradMin", DefaultPoiModerateGradMin);
                PoiModerateGradMax = source.Double("PoiModerateGradMax", DefaultPoiModerateGradMax);
                PoiErraticElevMinFrac = source.Double("PoiErraticElevMinFrac", DefaultPoiErraticElevMinFrac);
                PoiErraticElevMaxFrac = source.Double("PoiErraticElevMaxFrac", DefaultPoiErraticElevMaxFrac);
                PoiTreeElevMinFrac = source.Double("PoiTreeElevMinFrac", DefaultPoiTreeElevMinFrac);
                PoiTreeElevMaxFrac = source.Double("PoiTreeElevMaxFrac", DefaultPoiTreeElevMaxFrac);
                PoiTreeSettlementDist = source.Double("PoiTreeSettlementDist", DefaultPoiTreeSettlementDist);
                PoiChapelSettlementDist = source.Double("PoiChapelSettlementDist", DefaultPoiChapelSettlementDist);
                PoiTowerPeakDist = source.Double("PoiTowerPeakDist", DefaultPoiTowerPeakDist);
                PoiCairnPeakFrac = source.Double("PoiCairnPeakFrac", DefaultPoiCairnPeakFrac);
                PoiHeadlandShelterMax = source.Double("PoiHeadlandShelterMax", DefaultPoiHeadlandShelterMax);
                PoiJettyShelterMin = source.Double("PoiJettyShelterMin", DefaultPoiJettyShelterMin);
                DetailSheetWidthMm = source.Double("DetailSheetWidthMm", DefaultDetailSheetWidthMm);
                DetailSheetHeightMm = source.Double("DetailSheetHeightMm", DefaultDetailSheetHeightMm);
                DetailSheetMarginMm = source.Double("DetailSheetMarginMm", DefaultDetailSheetMarginMm);
                PoiScaleDenominator = source.Int("PoiScaleDenominator", DefaultPoiScaleDenominator);
            LoadedFrom = source.Path;
            problems = source.Problems;
            Refingerprint();
            parameters = BuildParameters();
        }

        /// <summary>Every parameter, in the order <c>Tuning.cs</c> declares them.</summary>
        public static IReadOnlyList<Parameter> Parameters { get { return parameters; } }
        static readonly IReadOnlyList<Parameter> parameters;

        /// <summary>The scopes, in file order. A grouping for anything presenting these to a
        /// human; generation itself never asks what scope a value is in.</summary>
        public static readonly IReadOnlyList<string> Scopes = new string[]
        {
            "domain_field",
            "falloff",
            "lattice_detail",
            "contouring",
            "quantisation",
            "paper",
            "hydrographic_coastal_strip",
            "scales",
            "grid",
            "service_rule",
            "cull",
            "rotation",
            "peaks",
            "settlements",
            "rivers",
            "soundings",
            "peak_lattice",
            "points_of_interest",
            "detail_sheets",
        };

        static IReadOnlyList<Parameter> BuildParameters()
        {
            return new Parameter[]
            {
                new Parameter("DomainMetres", "domain_field", false, DefaultDomainMetres, () => DomainMetres),
                new Parameter("NominalRadiusFrac", "domain_field", false, DefaultNominalRadiusFrac, () => NominalRadiusFrac),
                new Parameter("NominalRadiusJitter", "domain_field", false, DefaultNominalRadiusJitter, () => NominalRadiusJitter),
                new Parameter("SeaLevel", "domain_field", false, DefaultSeaLevel, () => SeaLevel),
                new Parameter("FeatureScale", "domain_field", false, DefaultFeatureScale, () => FeatureScale),
                new Parameter("WarpAmp", "domain_field", false, DefaultWarpAmp, () => WarpAmp),
                new Parameter("FbmOctaves", "domain_field", true, DefaultFbmOctaves, () => FbmOctaves),
                new Parameter("FbmLacunarity", "domain_field", false, DefaultFbmLacunarity, () => FbmLacunarity),
                new Parameter("FbmGain", "domain_field", false, DefaultFbmGain, () => FbmGain),
                new Parameter("MaxDepth", "domain_field", false, DefaultMaxDepth, () => MaxDepth),
                new Parameter("MountainousEdge0", "falloff", false, DefaultMountainousEdge0, () => MountainousEdge0),
                new Parameter("MountainousEdge1", "falloff", false, DefaultMountainousEdge1, () => MountainousEdge1),
                new Parameter("FjordedEdge0", "falloff", false, DefaultFjordedEdge0, () => FjordedEdge0),
                new Parameter("FjordedEdge1", "falloff", false, DefaultFjordedEdge1, () => FjordedEdge1),
                new Parameter("FjordedCutAmplitude", "falloff", false, DefaultFjordedCutAmplitude, () => FjordedCutAmplitude),
                new Parameter("FjordedCutFrequency", "falloff", false, DefaultFjordedCutFrequency, () => FjordedCutFrequency),
                new Parameter("AtollRingRadius", "falloff", false, DefaultAtollRingRadius, () => AtollRingRadius),
                new Parameter("AtollRingCore", "falloff", false, DefaultAtollRingCore, () => AtollRingCore),
                new Parameter("AtollRingWidth", "falloff", false, DefaultAtollRingWidth, () => AtollRingWidth),
                new Parameter("BaseCell", "lattice_detail", false, DefaultBaseCell, () => BaseCell),
                new Parameter("PaperDetailMm", "lattice_detail", false, DefaultPaperDetailMm, () => PaperDetailMm),
                new Parameter("MaxLod", "lattice_detail", true, DefaultMaxLod, () => MaxLod),
                new Parameter("ContourStep", "lattice_detail", false, DefaultContourStep, () => ContourStep),
                new Parameter("WeldFraction", "contouring", false, DefaultWeldFraction, () => WeldFraction),
                new Parameter("MmPerMetre", "contouring", false, DefaultMmPerMetre, () => MmPerMetre),
                new Parameter("MaxPaperContourLod", "contouring", true, DefaultMaxPaperContourLod, () => MaxPaperContourLod),
                new Parameter("CoastlineMarginCells", "contouring", true, DefaultCoastlineMarginCells, () => CoastlineMarginCells),
                new Parameter("GradientStep", "quantisation", false, DefaultGradientStep, () => GradientStep),
                new Parameter("SheetWidthMm", "paper", false, DefaultSheetWidthMm, () => SheetWidthMm),
                new Parameter("SheetHeightMm", "paper", false, DefaultSheetHeightMm, () => SheetHeightMm),
                new Parameter("SheetMarginMm", "paper", false, DefaultSheetMarginMm, () => SheetMarginMm),
                new Parameter("QuarterScaleFineDenominator", "scales", true, DefaultQuarterScaleFineDenominator, () => QuarterScaleFineDenominator),
                new Parameter("QuarterScaleDenominator", "scales", true, DefaultQuarterScaleDenominator, () => QuarterScaleDenominator),
                new Parameter("WholeIslandScaleDenominator", "scales", true, DefaultWholeIslandScaleDenominator, () => WholeIslandScaleDenominator),
                new Parameter("WholeIslandFallbackScaleDenominator", "scales", true, DefaultWholeIslandFallbackScaleDenominator, () => WholeIslandFallbackScaleDenominator),
                new Parameter("GridPitchPaperMm", "grid", false, DefaultGridPitchPaperMm, () => GridPitchPaperMm),
                new Parameter("ServiceRadiusFrac", "service_rule", false, DefaultServiceRadiusFrac, () => ServiceRadiusFrac),
                new Parameter("ServedThreshold", "service_rule", false, DefaultServedThreshold, () => ServedThreshold),
                new Parameter("SoundingDepth", "service_rule", false, DefaultSoundingDepth, () => SoundingDepth),
                new Parameter("CullSampleGrid", "cull", true, DefaultCullSampleGrid, () => CullSampleGrid),
                new Parameter("PeakElevationFrac", "peaks", false, DefaultPeakElevationFrac, () => PeakElevationFrac),
                new Parameter("PeakNmsRadius", "peaks", false, DefaultPeakNmsRadius, () => PeakNmsRadius),
                new Parameter("PeakNamedCount", "peaks", true, DefaultPeakNamedCount, () => PeakNamedCount),
                new Parameter("SettlementLattice", "settlements", false, DefaultSettlementLattice, () => SettlementLattice),
                new Parameter("SettlementCoastDist", "settlements", false, DefaultSettlementCoastDist, () => SettlementCoastDist),
                new Parameter("SettlementFlatGrad", "settlements", false, DefaultSettlementFlatGrad, () => SettlementFlatGrad),
                new Parameter("SettlementShelterRadius", "settlements", false, DefaultSettlementShelterRadius, () => SettlementShelterRadius),
                new Parameter("SettlementMinSpacing", "settlements", false, DefaultSettlementMinSpacing, () => SettlementMinSpacing),
                new Parameter("SettlementShelterWeight", "settlements", false, DefaultSettlementShelterWeight, () => SettlementShelterWeight),
                new Parameter("SettlementFlatnessWeight", "settlements", false, DefaultSettlementFlatnessWeight, () => SettlementFlatnessWeight),
                new Parameter("RiverStep", "rivers", false, DefaultRiverStep, () => RiverStep),
                new Parameter("RiverJitterRad", "rivers", false, DefaultRiverJitterRad, () => RiverJitterRad),
                new Parameter("RiverMergeDist", "rivers", false, DefaultRiverMergeDist, () => RiverMergeDist),
                new Parameter("RiverMaxSteps", "rivers", true, DefaultRiverMaxSteps, () => RiverMaxSteps),
                new Parameter("RiverMinLength", "rivers", false, DefaultRiverMinLength, () => RiverMinLength),
                new Parameter("SoundingLattice", "soundings", false, DefaultSoundingLattice, () => SoundingLattice),
                new Parameter("PeakLattice", "peak_lattice", false, DefaultPeakLattice, () => PeakLattice),
                new Parameter("PoiLattice", "points_of_interest", false, DefaultPoiLattice, () => PoiLattice),
                new Parameter("PoiMinSpacing", "points_of_interest", false, DefaultPoiMinSpacing, () => PoiMinSpacing),
                new Parameter("PoiCountMountainousMin", "points_of_interest", true, DefaultPoiCountMountainousMin, () => PoiCountMountainousMin),
                new Parameter("PoiCountMountainousMax", "points_of_interest", true, DefaultPoiCountMountainousMax, () => PoiCountMountainousMax),
                new Parameter("PoiCountFjordedMin", "points_of_interest", true, DefaultPoiCountFjordedMin, () => PoiCountFjordedMin),
                new Parameter("PoiCountFjordedMax", "points_of_interest", true, DefaultPoiCountFjordedMax, () => PoiCountFjordedMax),
                new Parameter("PoiCountAtollMin", "points_of_interest", true, DefaultPoiCountAtollMin, () => PoiCountAtollMin),
                new Parameter("PoiCountAtollMax", "points_of_interest", true, DefaultPoiCountAtollMax, () => PoiCountAtollMax),
                new Parameter("PoiShoreBand", "points_of_interest", false, DefaultPoiShoreBand, () => PoiShoreBand),
                new Parameter("PoiSteepShoreGrad", "points_of_interest", false, DefaultPoiSteepShoreGrad, () => PoiSteepShoreGrad),
                new Parameter("PoiSeaArchGrad", "points_of_interest", false, DefaultPoiSeaArchGrad, () => PoiSeaArchGrad),
                new Parameter("PoiBlowholeCoastDist", "points_of_interest", false, DefaultPoiBlowholeCoastDist, () => PoiBlowholeCoastDist),
                new Parameter("PoiSpringMinElevation", "points_of_interest", false, DefaultPoiSpringMinElevation, () => PoiSpringMinElevation),
                new Parameter("PoiSpringConvergence", "points_of_interest", false, DefaultPoiSpringConvergence, () => PoiSpringConvergence),
                new Parameter("PoiOpenGrad", "points_of_interest", false, DefaultPoiOpenGrad, () => PoiOpenGrad),
                new Parameter("PoiFlatGrad", "points_of_interest", false, DefaultPoiFlatGrad, () => PoiFlatGrad),
                new Parameter("PoiModerateGradMin", "points_of_interest", false, DefaultPoiModerateGradMin, () => PoiModerateGradMin),
                new Parameter("PoiModerateGradMax", "points_of_interest", false, DefaultPoiModerateGradMax, () => PoiModerateGradMax),
                new Parameter("PoiErraticElevMinFrac", "points_of_interest", false, DefaultPoiErraticElevMinFrac, () => PoiErraticElevMinFrac),
                new Parameter("PoiErraticElevMaxFrac", "points_of_interest", false, DefaultPoiErraticElevMaxFrac, () => PoiErraticElevMaxFrac),
                new Parameter("PoiTreeElevMinFrac", "points_of_interest", false, DefaultPoiTreeElevMinFrac, () => PoiTreeElevMinFrac),
                new Parameter("PoiTreeElevMaxFrac", "points_of_interest", false, DefaultPoiTreeElevMaxFrac, () => PoiTreeElevMaxFrac),
                new Parameter("PoiTreeSettlementDist", "points_of_interest", false, DefaultPoiTreeSettlementDist, () => PoiTreeSettlementDist),
                new Parameter("PoiChapelSettlementDist", "points_of_interest", false, DefaultPoiChapelSettlementDist, () => PoiChapelSettlementDist),
                new Parameter("PoiTowerPeakDist", "points_of_interest", false, DefaultPoiTowerPeakDist, () => PoiTowerPeakDist),
                new Parameter("PoiCairnPeakFrac", "points_of_interest", false, DefaultPoiCairnPeakFrac, () => PoiCairnPeakFrac),
                new Parameter("PoiHeadlandShelterMax", "points_of_interest", false, DefaultPoiHeadlandShelterMax, () => PoiHeadlandShelterMax),
                new Parameter("PoiJettyShelterMin", "points_of_interest", false, DefaultPoiJettyShelterMin, () => PoiJettyShelterMin),
                new Parameter("DetailSheetWidthMm", "detail_sheets", false, DefaultDetailSheetWidthMm, () => DetailSheetWidthMm),
                new Parameter("DetailSheetHeightMm", "detail_sheets", false, DefaultDetailSheetHeightMm, () => DetailSheetHeightMm),
                new Parameter("DetailSheetMarginMm", "detail_sheets", false, DefaultDetailSheetMarginMm, () => DetailSheetMarginMm),
                new Parameter("PoiScaleDenominator", "detail_sheets", true, DefaultPoiScaleDenominator, () => PoiScaleDenominator),
            };
        }

#if UNITY_EDITOR
        /// <summary>
        /// The write side, editor only, keyed by the same name the config file uses.
        ///
        /// <para>A dictionary of setters rather than a setter carried inside every
        /// <see cref="Parameter"/>: that would make the struct's shape differ between the two
        /// builds, and a type whose fields depend on a compilation symbol is a type that
        /// compiles in one configuration and not the other, found at the worst moment. The
        /// struct is identical in both builds; only this table and
        /// <see cref="Parameter.Set"/> are conditional.</para>
        ///
        /// <para>Integers round rather than truncate: a window showing 5 and storing 4.999
        /// would be a bug nobody could see.</para>
        /// </summary>
        static readonly Dictionary<string, Action<double>> setters = new Dictionary<string, Action<double>>
        {
            { "DomainMetres", v => DomainMetres = v },
            { "NominalRadiusFrac", v => NominalRadiusFrac = v },
            { "NominalRadiusJitter", v => NominalRadiusJitter = v },
            { "SeaLevel", v => SeaLevel = v },
            { "FeatureScale", v => FeatureScale = v },
            { "WarpAmp", v => WarpAmp = v },
            { "FbmOctaves", v => FbmOctaves = (int)System.Math.Round(v) },
            { "FbmLacunarity", v => FbmLacunarity = v },
            { "FbmGain", v => FbmGain = v },
            { "MaxDepth", v => MaxDepth = v },
            { "MountainousEdge0", v => MountainousEdge0 = v },
            { "MountainousEdge1", v => MountainousEdge1 = v },
            { "FjordedEdge0", v => FjordedEdge0 = v },
            { "FjordedEdge1", v => FjordedEdge1 = v },
            { "FjordedCutAmplitude", v => FjordedCutAmplitude = v },
            { "FjordedCutFrequency", v => FjordedCutFrequency = v },
            { "AtollRingRadius", v => AtollRingRadius = v },
            { "AtollRingCore", v => AtollRingCore = v },
            { "AtollRingWidth", v => AtollRingWidth = v },
            { "BaseCell", v => BaseCell = v },
            { "PaperDetailMm", v => PaperDetailMm = v },
            { "MaxLod", v => MaxLod = (int)System.Math.Round(v) },
            { "ContourStep", v => ContourStep = v },
            { "WeldFraction", v => WeldFraction = v },
            { "MmPerMetre", v => MmPerMetre = v },
            { "MaxPaperContourLod", v => MaxPaperContourLod = (int)System.Math.Round(v) },
            { "CoastlineMarginCells", v => CoastlineMarginCells = (int)System.Math.Round(v) },
            { "GradientStep", v => GradientStep = v },
            { "SheetWidthMm", v => SheetWidthMm = v },
            { "SheetHeightMm", v => SheetHeightMm = v },
            { "SheetMarginMm", v => SheetMarginMm = v },
            { "QuarterScaleFineDenominator", v => QuarterScaleFineDenominator = (int)System.Math.Round(v) },
            { "QuarterScaleDenominator", v => QuarterScaleDenominator = (int)System.Math.Round(v) },
            { "WholeIslandScaleDenominator", v => WholeIslandScaleDenominator = (int)System.Math.Round(v) },
            { "WholeIslandFallbackScaleDenominator", v => WholeIslandFallbackScaleDenominator = (int)System.Math.Round(v) },
            { "GridPitchPaperMm", v => GridPitchPaperMm = v },
            { "ServiceRadiusFrac", v => ServiceRadiusFrac = v },
            { "ServedThreshold", v => ServedThreshold = v },
            { "SoundingDepth", v => SoundingDepth = v },
            { "CullSampleGrid", v => CullSampleGrid = (int)System.Math.Round(v) },
            { "PeakElevationFrac", v => PeakElevationFrac = v },
            { "PeakNmsRadius", v => PeakNmsRadius = v },
            { "PeakNamedCount", v => PeakNamedCount = (int)System.Math.Round(v) },
            { "SettlementLattice", v => SettlementLattice = v },
            { "SettlementCoastDist", v => SettlementCoastDist = v },
            { "SettlementFlatGrad", v => SettlementFlatGrad = v },
            { "SettlementShelterRadius", v => SettlementShelterRadius = v },
            { "SettlementMinSpacing", v => SettlementMinSpacing = v },
            { "SettlementShelterWeight", v => SettlementShelterWeight = v },
            { "SettlementFlatnessWeight", v => SettlementFlatnessWeight = v },
            { "RiverStep", v => RiverStep = v },
            { "RiverJitterRad", v => RiverJitterRad = v },
            { "RiverMergeDist", v => RiverMergeDist = v },
            { "RiverMaxSteps", v => RiverMaxSteps = (int)System.Math.Round(v) },
            { "RiverMinLength", v => RiverMinLength = v },
            { "SoundingLattice", v => SoundingLattice = v },
            { "PeakLattice", v => PeakLattice = v },
            { "PoiLattice", v => PoiLattice = v },
            { "PoiMinSpacing", v => PoiMinSpacing = v },
            { "PoiCountMountainousMin", v => PoiCountMountainousMin = (int)System.Math.Round(v) },
            { "PoiCountMountainousMax", v => PoiCountMountainousMax = (int)System.Math.Round(v) },
            { "PoiCountFjordedMin", v => PoiCountFjordedMin = (int)System.Math.Round(v) },
            { "PoiCountFjordedMax", v => PoiCountFjordedMax = (int)System.Math.Round(v) },
            { "PoiCountAtollMin", v => PoiCountAtollMin = (int)System.Math.Round(v) },
            { "PoiCountAtollMax", v => PoiCountAtollMax = (int)System.Math.Round(v) },
            { "PoiShoreBand", v => PoiShoreBand = v },
            { "PoiSteepShoreGrad", v => PoiSteepShoreGrad = v },
            { "PoiSeaArchGrad", v => PoiSeaArchGrad = v },
            { "PoiBlowholeCoastDist", v => PoiBlowholeCoastDist = v },
            { "PoiSpringMinElevation", v => PoiSpringMinElevation = v },
            { "PoiSpringConvergence", v => PoiSpringConvergence = v },
            { "PoiOpenGrad", v => PoiOpenGrad = v },
            { "PoiFlatGrad", v => PoiFlatGrad = v },
            { "PoiModerateGradMin", v => PoiModerateGradMin = v },
            { "PoiModerateGradMax", v => PoiModerateGradMax = v },
            { "PoiErraticElevMinFrac", v => PoiErraticElevMinFrac = v },
            { "PoiErraticElevMaxFrac", v => PoiErraticElevMaxFrac = v },
            { "PoiTreeElevMinFrac", v => PoiTreeElevMinFrac = v },
            { "PoiTreeElevMaxFrac", v => PoiTreeElevMaxFrac = v },
            { "PoiTreeSettlementDist", v => PoiTreeSettlementDist = v },
            { "PoiChapelSettlementDist", v => PoiChapelSettlementDist = v },
            { "PoiTowerPeakDist", v => PoiTowerPeakDist = v },
            { "PoiCairnPeakFrac", v => PoiCairnPeakFrac = v },
            { "PoiHeadlandShelterMax", v => PoiHeadlandShelterMax = v },
            { "PoiJettyShelterMin", v => PoiJettyShelterMin = v },
            { "DetailSheetWidthMm", v => DetailSheetWidthMm = v },
            { "DetailSheetHeightMm", v => DetailSheetHeightMm = v },
            { "DetailSheetMarginMm", v => DetailSheetMarginMm = v },
            { "PoiScaleDenominator", v => PoiScaleDenominator = (int)System.Math.Round(v) },
        };

        /// <summary>Sets one value by name. Unknown names are ignored rather than thrown on —
        /// the callers are UI, and a window that throws in OnGUI throws every frame.</summary>
        internal static void SetByName(string name, double value)
        {
            Action<double> write;
            if (name == null || !setters.TryGetValue(name, out write)) return;

            write(value);
            Refingerprint();
        }

        /// <summary>Re-reads the config file and applies it over the defaults.</summary>
        public static void Reload()
        {
            TuningFile.Source source = TuningFile.Load();
                DomainMetres = source.Double("DomainMetres", DefaultDomainMetres);
                NominalRadiusFrac = source.Double("NominalRadiusFrac", DefaultNominalRadiusFrac);
                NominalRadiusJitter = source.Double("NominalRadiusJitter", DefaultNominalRadiusJitter);
                SeaLevel = source.Double("SeaLevel", DefaultSeaLevel);
                FeatureScale = source.Double("FeatureScale", DefaultFeatureScale);
                WarpAmp = source.Double("WarpAmp", DefaultWarpAmp);
                FbmOctaves = source.Int("FbmOctaves", DefaultFbmOctaves);
                FbmLacunarity = source.Double("FbmLacunarity", DefaultFbmLacunarity);
                FbmGain = source.Double("FbmGain", DefaultFbmGain);
                MaxDepth = source.Double("MaxDepth", DefaultMaxDepth);
                MountainousEdge0 = source.Double("MountainousEdge0", DefaultMountainousEdge0);
                MountainousEdge1 = source.Double("MountainousEdge1", DefaultMountainousEdge1);
                FjordedEdge0 = source.Double("FjordedEdge0", DefaultFjordedEdge0);
                FjordedEdge1 = source.Double("FjordedEdge1", DefaultFjordedEdge1);
                FjordedCutAmplitude = source.Double("FjordedCutAmplitude", DefaultFjordedCutAmplitude);
                FjordedCutFrequency = source.Double("FjordedCutFrequency", DefaultFjordedCutFrequency);
                AtollRingRadius = source.Double("AtollRingRadius", DefaultAtollRingRadius);
                AtollRingCore = source.Double("AtollRingCore", DefaultAtollRingCore);
                AtollRingWidth = source.Double("AtollRingWidth", DefaultAtollRingWidth);
                BaseCell = source.Double("BaseCell", DefaultBaseCell);
                PaperDetailMm = source.Double("PaperDetailMm", DefaultPaperDetailMm);
                MaxLod = source.Int("MaxLod", DefaultMaxLod);
                ContourStep = source.Double("ContourStep", DefaultContourStep);
                WeldFraction = source.Double("WeldFraction", DefaultWeldFraction);
                MmPerMetre = source.Double("MmPerMetre", DefaultMmPerMetre);
                MaxPaperContourLod = source.Int("MaxPaperContourLod", DefaultMaxPaperContourLod);
                CoastlineMarginCells = source.Int("CoastlineMarginCells", DefaultCoastlineMarginCells);
                GradientStep = source.Double("GradientStep", DefaultGradientStep);
                SheetWidthMm = source.Double("SheetWidthMm", DefaultSheetWidthMm);
                SheetHeightMm = source.Double("SheetHeightMm", DefaultSheetHeightMm);
                SheetMarginMm = source.Double("SheetMarginMm", DefaultSheetMarginMm);
                QuarterScaleFineDenominator = source.Int("QuarterScaleFineDenominator", DefaultQuarterScaleFineDenominator);
                QuarterScaleDenominator = source.Int("QuarterScaleDenominator", DefaultQuarterScaleDenominator);
                WholeIslandScaleDenominator = source.Int("WholeIslandScaleDenominator", DefaultWholeIslandScaleDenominator);
                WholeIslandFallbackScaleDenominator = source.Int("WholeIslandFallbackScaleDenominator", DefaultWholeIslandFallbackScaleDenominator);
                GridPitchPaperMm = source.Double("GridPitchPaperMm", DefaultGridPitchPaperMm);
                ServiceRadiusFrac = source.Double("ServiceRadiusFrac", DefaultServiceRadiusFrac);
                ServedThreshold = source.Double("ServedThreshold", DefaultServedThreshold);
                SoundingDepth = source.Double("SoundingDepth", DefaultSoundingDepth);
                CullSampleGrid = source.Int("CullSampleGrid", DefaultCullSampleGrid);
                PeakElevationFrac = source.Double("PeakElevationFrac", DefaultPeakElevationFrac);
                PeakNmsRadius = source.Double("PeakNmsRadius", DefaultPeakNmsRadius);
                PeakNamedCount = source.Int("PeakNamedCount", DefaultPeakNamedCount);
                SettlementLattice = source.Double("SettlementLattice", DefaultSettlementLattice);
                SettlementCoastDist = source.Double("SettlementCoastDist", DefaultSettlementCoastDist);
                SettlementFlatGrad = source.Double("SettlementFlatGrad", DefaultSettlementFlatGrad);
                SettlementShelterRadius = source.Double("SettlementShelterRadius", DefaultSettlementShelterRadius);
                SettlementMinSpacing = source.Double("SettlementMinSpacing", DefaultSettlementMinSpacing);
                SettlementShelterWeight = source.Double("SettlementShelterWeight", DefaultSettlementShelterWeight);
                SettlementFlatnessWeight = source.Double("SettlementFlatnessWeight", DefaultSettlementFlatnessWeight);
                RiverStep = source.Double("RiverStep", DefaultRiverStep);
                RiverJitterRad = source.Double("RiverJitterRad", DefaultRiverJitterRad);
                RiverMergeDist = source.Double("RiverMergeDist", DefaultRiverMergeDist);
                RiverMaxSteps = source.Int("RiverMaxSteps", DefaultRiverMaxSteps);
                RiverMinLength = source.Double("RiverMinLength", DefaultRiverMinLength);
                SoundingLattice = source.Double("SoundingLattice", DefaultSoundingLattice);
                PeakLattice = source.Double("PeakLattice", DefaultPeakLattice);
                PoiLattice = source.Double("PoiLattice", DefaultPoiLattice);
                PoiMinSpacing = source.Double("PoiMinSpacing", DefaultPoiMinSpacing);
                PoiCountMountainousMin = source.Int("PoiCountMountainousMin", DefaultPoiCountMountainousMin);
                PoiCountMountainousMax = source.Int("PoiCountMountainousMax", DefaultPoiCountMountainousMax);
                PoiCountFjordedMin = source.Int("PoiCountFjordedMin", DefaultPoiCountFjordedMin);
                PoiCountFjordedMax = source.Int("PoiCountFjordedMax", DefaultPoiCountFjordedMax);
                PoiCountAtollMin = source.Int("PoiCountAtollMin", DefaultPoiCountAtollMin);
                PoiCountAtollMax = source.Int("PoiCountAtollMax", DefaultPoiCountAtollMax);
                PoiShoreBand = source.Double("PoiShoreBand", DefaultPoiShoreBand);
                PoiSteepShoreGrad = source.Double("PoiSteepShoreGrad", DefaultPoiSteepShoreGrad);
                PoiSeaArchGrad = source.Double("PoiSeaArchGrad", DefaultPoiSeaArchGrad);
                PoiBlowholeCoastDist = source.Double("PoiBlowholeCoastDist", DefaultPoiBlowholeCoastDist);
                PoiSpringMinElevation = source.Double("PoiSpringMinElevation", DefaultPoiSpringMinElevation);
                PoiSpringConvergence = source.Double("PoiSpringConvergence", DefaultPoiSpringConvergence);
                PoiOpenGrad = source.Double("PoiOpenGrad", DefaultPoiOpenGrad);
                PoiFlatGrad = source.Double("PoiFlatGrad", DefaultPoiFlatGrad);
                PoiModerateGradMin = source.Double("PoiModerateGradMin", DefaultPoiModerateGradMin);
                PoiModerateGradMax = source.Double("PoiModerateGradMax", DefaultPoiModerateGradMax);
                PoiErraticElevMinFrac = source.Double("PoiErraticElevMinFrac", DefaultPoiErraticElevMinFrac);
                PoiErraticElevMaxFrac = source.Double("PoiErraticElevMaxFrac", DefaultPoiErraticElevMaxFrac);
                PoiTreeElevMinFrac = source.Double("PoiTreeElevMinFrac", DefaultPoiTreeElevMinFrac);
                PoiTreeElevMaxFrac = source.Double("PoiTreeElevMaxFrac", DefaultPoiTreeElevMaxFrac);
                PoiTreeSettlementDist = source.Double("PoiTreeSettlementDist", DefaultPoiTreeSettlementDist);
                PoiChapelSettlementDist = source.Double("PoiChapelSettlementDist", DefaultPoiChapelSettlementDist);
                PoiTowerPeakDist = source.Double("PoiTowerPeakDist", DefaultPoiTowerPeakDist);
                PoiCairnPeakFrac = source.Double("PoiCairnPeakFrac", DefaultPoiCairnPeakFrac);
                PoiHeadlandShelterMax = source.Double("PoiHeadlandShelterMax", DefaultPoiHeadlandShelterMax);
                PoiJettyShelterMin = source.Double("PoiJettyShelterMin", DefaultPoiJettyShelterMin);
                DetailSheetWidthMm = source.Double("DetailSheetWidthMm", DefaultDetailSheetWidthMm);
                DetailSheetHeightMm = source.Double("DetailSheetHeightMm", DefaultDetailSheetHeightMm);
                DetailSheetMarginMm = source.Double("DetailSheetMarginMm", DefaultDetailSheetMarginMm);
                PoiScaleDenominator = source.Int("PoiScaleDenominator", DefaultPoiScaleDenominator);
            LoadedFrom = source.Path;
            problems = source.Problems;
            Refingerprint();
        }
#else
        /// <summary>Does nothing outside the editor: the values are <c>static readonly</c> and
        /// a shipped game has no business changing what its seeds mean mid-session. Present
        /// rather than absent so callers do not need their own <c>#if</c>.</summary>
        public static void Reload() { }
#endif

        /// <summary>
        /// One tuning value, described well enough for a window to draw it and for the config
        /// file to be written from it.
        ///
        /// <para>Everything is a <c>double</c>, including the integers, because a table that
        /// is uniform is a table a UI can walk. <see cref="IsInteger"/> says how to present and
        /// round it; the setter behind <see cref="Set"/> does the rounding, so a caller cannot
        /// forget.</para>
        /// </summary>
        public readonly struct Parameter
        {
            readonly Func<double> read;

            public string Name { get; }
            public string Scope { get; }
            public bool IsInteger { get; }

            /// <summary>The literal compiled into <c>Tuning.cs</c> — what applies when no config
            /// file is found.</summary>
            public double Default { get; }

            public Parameter(string name, string scope, bool isInteger, double defaultValue,
                             Func<double> read)
            {
                Name = name; Scope = scope; IsInteger = isInteger;
                Default = defaultValue; this.read = read;
            }

            /// <summary>The live value.</summary>
            public double Value { get { return read(); } }

            /// <summary>True when the config file has moved this off its default.</summary>
            public bool IsOverridden { get { return Value != Default; } }

#if UNITY_EDITOR
            /// <summary>Editor only — see the class comment on why the player's values cannot
            /// be written.</summary>
            public void Set(double value) { SetByName(Name, value); }
#endif

            public override string ToString()
            {
                return $"{Scope}.{Name} = {Value.ToString("R", CultureInfo.InvariantCulture)}";
            }
        }

        /// <summary>The config file the live values came from, or null when none was found and
        /// the defaults are in force.</summary>
        public static string LoadedFrom { get; private set; }

        static IReadOnlyList<string> problems;

        /// <summary>What was wrong with the file: unknown keys, values that would not parse, a
        /// key filed under a surprising scope. Empty is the normal case.</summary>
        public static IReadOnlyList<string> Problems { get { return problems; } }

        /// <summary>
        /// A hash of every live value. Two runs agreeing on this agree on what every seed in
        /// the archive means; two runs disagreeing do not, however identical their seeds.
        ///
        /// <para>Round-trip formatting under the invariant culture, so the same file cannot
        /// fingerprint differently on a machine whose decimal separator is a comma.</para>
        /// </summary>
        public static ulong Fingerprint { get; private set; }

        static void Refingerprint()
        {
            ulong h = 14695981039346656037UL;   // FNV-1a offset basis
            Mix(ref h, "DomainMetres", DomainMetres);
            Mix(ref h, "NominalRadiusFrac", NominalRadiusFrac);
            Mix(ref h, "NominalRadiusJitter", NominalRadiusJitter);
            Mix(ref h, "SeaLevel", SeaLevel);
            Mix(ref h, "FeatureScale", FeatureScale);
            Mix(ref h, "WarpAmp", WarpAmp);
            Mix(ref h, "FbmOctaves", FbmOctaves);
            Mix(ref h, "FbmLacunarity", FbmLacunarity);
            Mix(ref h, "FbmGain", FbmGain);
            Mix(ref h, "MaxDepth", MaxDepth);
            Mix(ref h, "MountainousEdge0", MountainousEdge0);
            Mix(ref h, "MountainousEdge1", MountainousEdge1);
            Mix(ref h, "FjordedEdge0", FjordedEdge0);
            Mix(ref h, "FjordedEdge1", FjordedEdge1);
            Mix(ref h, "FjordedCutAmplitude", FjordedCutAmplitude);
            Mix(ref h, "FjordedCutFrequency", FjordedCutFrequency);
            Mix(ref h, "AtollRingRadius", AtollRingRadius);
            Mix(ref h, "AtollRingCore", AtollRingCore);
            Mix(ref h, "AtollRingWidth", AtollRingWidth);
            Mix(ref h, "BaseCell", BaseCell);
            Mix(ref h, "PaperDetailMm", PaperDetailMm);
            Mix(ref h, "MaxLod", MaxLod);
            Mix(ref h, "ContourStep", ContourStep);
            Mix(ref h, "WeldFraction", WeldFraction);
            Mix(ref h, "MmPerMetre", MmPerMetre);
            Mix(ref h, "MaxPaperContourLod", MaxPaperContourLod);
            Mix(ref h, "CoastlineMarginCells", CoastlineMarginCells);
            Mix(ref h, "GradientStep", GradientStep);
            Mix(ref h, "SheetWidthMm", SheetWidthMm);
            Mix(ref h, "SheetHeightMm", SheetHeightMm);
            Mix(ref h, "SheetMarginMm", SheetMarginMm);
            Mix(ref h, "QuarterScaleFineDenominator", QuarterScaleFineDenominator);
            Mix(ref h, "QuarterScaleDenominator", QuarterScaleDenominator);
            Mix(ref h, "WholeIslandScaleDenominator", WholeIslandScaleDenominator);
            Mix(ref h, "WholeIslandFallbackScaleDenominator", WholeIslandFallbackScaleDenominator);
            Mix(ref h, "GridPitchPaperMm", GridPitchPaperMm);
            Mix(ref h, "ServiceRadiusFrac", ServiceRadiusFrac);
            Mix(ref h, "ServedThreshold", ServedThreshold);
            Mix(ref h, "SoundingDepth", SoundingDepth);
            Mix(ref h, "CullSampleGrid", CullSampleGrid);
            Mix(ref h, "PeakElevationFrac", PeakElevationFrac);
            Mix(ref h, "PeakNmsRadius", PeakNmsRadius);
            Mix(ref h, "PeakNamedCount", PeakNamedCount);
            Mix(ref h, "SettlementLattice", SettlementLattice);
            Mix(ref h, "SettlementCoastDist", SettlementCoastDist);
            Mix(ref h, "SettlementFlatGrad", SettlementFlatGrad);
            Mix(ref h, "SettlementShelterRadius", SettlementShelterRadius);
            Mix(ref h, "SettlementMinSpacing", SettlementMinSpacing);
            Mix(ref h, "SettlementShelterWeight", SettlementShelterWeight);
            Mix(ref h, "SettlementFlatnessWeight", SettlementFlatnessWeight);
            Mix(ref h, "RiverStep", RiverStep);
            Mix(ref h, "RiverJitterRad", RiverJitterRad);
            Mix(ref h, "RiverMergeDist", RiverMergeDist);
            Mix(ref h, "RiverMaxSteps", RiverMaxSteps);
            Mix(ref h, "RiverMinLength", RiverMinLength);
            Mix(ref h, "SoundingLattice", SoundingLattice);
            Mix(ref h, "PeakLattice", PeakLattice);
            Mix(ref h, "PoiLattice", PoiLattice);
            Mix(ref h, "PoiMinSpacing", PoiMinSpacing);
            Mix(ref h, "PoiCountMountainousMin", PoiCountMountainousMin);
            Mix(ref h, "PoiCountMountainousMax", PoiCountMountainousMax);
            Mix(ref h, "PoiCountFjordedMin", PoiCountFjordedMin);
            Mix(ref h, "PoiCountFjordedMax", PoiCountFjordedMax);
            Mix(ref h, "PoiCountAtollMin", PoiCountAtollMin);
            Mix(ref h, "PoiCountAtollMax", PoiCountAtollMax);
            Mix(ref h, "PoiShoreBand", PoiShoreBand);
            Mix(ref h, "PoiSteepShoreGrad", PoiSteepShoreGrad);
            Mix(ref h, "PoiSeaArchGrad", PoiSeaArchGrad);
            Mix(ref h, "PoiBlowholeCoastDist", PoiBlowholeCoastDist);
            Mix(ref h, "PoiSpringMinElevation", PoiSpringMinElevation);
            Mix(ref h, "PoiSpringConvergence", PoiSpringConvergence);
            Mix(ref h, "PoiOpenGrad", PoiOpenGrad);
            Mix(ref h, "PoiFlatGrad", PoiFlatGrad);
            Mix(ref h, "PoiModerateGradMin", PoiModerateGradMin);
            Mix(ref h, "PoiModerateGradMax", PoiModerateGradMax);
            Mix(ref h, "PoiErraticElevMinFrac", PoiErraticElevMinFrac);
            Mix(ref h, "PoiErraticElevMaxFrac", PoiErraticElevMaxFrac);
            Mix(ref h, "PoiTreeElevMinFrac", PoiTreeElevMinFrac);
            Mix(ref h, "PoiTreeElevMaxFrac", PoiTreeElevMaxFrac);
            Mix(ref h, "PoiTreeSettlementDist", PoiTreeSettlementDist);
            Mix(ref h, "PoiChapelSettlementDist", PoiChapelSettlementDist);
            Mix(ref h, "PoiTowerPeakDist", PoiTowerPeakDist);
            Mix(ref h, "PoiCairnPeakFrac", PoiCairnPeakFrac);
            Mix(ref h, "PoiHeadlandShelterMax", PoiHeadlandShelterMax);
            Mix(ref h, "PoiJettyShelterMin", PoiJettyShelterMin);
            Mix(ref h, "DetailSheetWidthMm", DetailSheetWidthMm);
            Mix(ref h, "DetailSheetHeightMm", DetailSheetHeightMm);
            Mix(ref h, "DetailSheetMarginMm", DetailSheetMarginMm);
            Mix(ref h, "PoiScaleDenominator", PoiScaleDenominator);
            Fingerprint = h;
        }

        static void Mix(ref ulong h, string name, double value)
        {
            Mix(ref h, name);
            Mix(ref h, value.ToString("R", CultureInfo.InvariantCulture));
        }

        static void Mix(ref ulong h, string s)
        {
            for (int i = 0; i < s.Length; i++)
            {
                h ^= s[i];
                h *= 1099511628211UL;
            }
            h ^= (byte)'|';
            h *= 1099511628211UL;
        }

        /// <summary>One line for a log: where the numbers came from and what they add up to.</summary>
        public static string Describe()
        {
            string source = LoadedFrom ?? "compiled defaults";
            int overridden = 0;
            for (int i = 0; i < parameters.Count; i++) if (parameters[i].IsOverridden) overridden++;

            string faults = problems.Count == 0 ? "" : $", {problems.Count} problem(s)";
            return $"tuning {Fingerprint:X16} from {source} ({overridden} overridden{faults})";
        }
    }
}
